version: "3.7"

services:
  # Matomo doesn't work with psql, so we use mysql instead
  # See https://matomo.org/faq/how-to-install/faq_55/
  mysql:
    image: mysql:8-debian
    environment:
      # Allowing empty root password for local development only.
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: matomo
      MYSQL_USER: matomo
      MYSQL_PASSWORD: more_secret_local_passwords
    healthcheck:
      test: "mysqladmin ping | grep 'mysqld is alive'"
      timeout: 10s
      retries: 20
    init: true
    volumes:
      - mysql_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

  install:
    build:
      target: install
      context: install
    environment:
      MATOMO_DATABASE_HOST: mysql
      MATOMO_DATABASE_USERNAME: matomo
      MATOMO_DATABASE_PASSWORD: more_secret_local_passwords
      MATOMO_DATABASE_DBNAME: matomo
    # command: ["php", "./console", "-n", "matomo:install", "--install-file=install.json"]
    # command: systemctl start apache2 && php ./console -n matomo:install --install-file=install.json
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8081:80
    profiles:
      - install
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./install/install.json:/var/www/html/install.json
      - ./config.ini.php:/var/www/html/config/config.ini.php

  matomo:
    image: matomo:4.14.1
    environment:
      MATOMO_DATABASE_HOST: mysql
      MATOMO_DATABASE_USERNAME: matomo
      MATOMO_DATABASE_PASSWORD: more_secret_local_passwords
      MATOMO_DATABASE_DBNAME: matomo
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8080:80
    profiles:
      - prod
    volumes:
      - matomo_data:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - ./config.ini.php:/var/www/html/config/config.ini.php

volumes:
  mysql_data:
  matomo_data:
