version: "3.7"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: incredible_local_secret_phrase
      POSTGRES_USER: postgres
    healthcheck:
      test: "pg_isready --username=postgres"
      timeout: 10s
      retries: 20
    init: true
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  remix_dev:
    build:
      target: dev
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:incredible_local_secret_phrase@postgres:5432/postgres?schema=public
    init: true
    ports:
      - "3003:3000"
      - "6066:6006"
    volumes:
      # Selectively mount directories for faster local development.
      - ./app:/home/node/remix/app
      - ./prisma:/home/node/remix/prisma

  remix_prod:
    build:
      target: prod
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:incredible_local_secret_phrase@postgres:5432/postgres?schema=public
    init: true
    ports:
      - "3010:3000"
    read_only: true
    volumes:
      - remix_prod_tmp:/tmp

volumes:
  remix_dev_nodemodules:
  remix_prod_tmp:
  postgres_data:
