FROM mcr.microsoft.com/playwright:v1.31.0-focal
WORKDIR /srv
RUN npm install @playwright/test @axe-core/playwright
COPY playwright.config.ts .
COPY e2e e2e
CMD [ "npx", "playwright", "test", "--retries=3" ]
