version: "3.7"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: incredible_local_secret_phrase
      POSTGRES_USER: postgres
    healthcheck:
      test: "pg_isready --username=postgres"
      timeout: 10s
      retries: 20
    init: true
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  remix_dev:
    build:
      target: dev
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:incredible_local_secret_phrase@postgres:5432/postgres?schema=public
    init: true
    ports:
      - "3003:3000"
      - "6066:6006"
    volumes:
      # Mount the app directory for faster local development.
      - ./:/home/node/remix
      # Use a named volume for the node_modules so that the container uses the guest machine's node_modules dir instead of the host machine's node_modules directory, which might be divergent.
      - remix_dev_nodemodules:/home/node/remix/node_modules

  remix_prod:
    build:
      target: prod
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:incredible_local_secret_phrase@postgres:5432/postgres?schema=public
    init: true
    ports:
      - "3010:3000"

volumes:
  remix_dev_nodemodules:
  postgres_data:
