version: "3.7"

services:
  remix-migrate-reset:
    build:
      target: dev
      context: .
    environment:
      DATABASE_URL: postgresql://postgres:incredible_local_secret_phrase@database-e2e:5432/postgres?schema=public
    depends_on:
      database-e2e:
        condition: service_healthy
    networks:
      - participant_portal-e2e
    command: >
      bash -c "npx prisma migrate reset --force"
  database-e2e:
    image: postgres
    environment:
      POSTGRES_PASSWORD: incredible_local_secret_phrase
      POSTGRES_USER: postgres
    healthcheck:
      test: "pg_isready --username=postgres"
      timeout: 5s
      retries: 20
    ports:
      - 5555:5432
    networks:
      - participant_portal-e2e
networks:
  participant_portal-e2e:
