name: 📬 Deploy participant

on:
  push:
    branches: ["main"]
    paths:
      - participant/**

jobs:
  deploy_participant:
    name: 📬 Deploy participant
    uses: ./.github/workflows/cd.yml
    with:
      app_name: participant
