name: 🧪 CI - Staff Portal
on:
  push:
    branches:
      - main
    paths:
      - staff/**
      - .github/workflows/ci-staff-portal.yml
  pull_request:
    paths:
      - staff/**
      - .github/workflows/ci-staff-portal.yml

jobs:
  # No typescript to lint yet!
  # lint:
  #   name: ⬣ ESLint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: ⬇️ Checkout repo
  #       uses: actions/checkout@v3

  #     - name: ⎔ Setup node
  #       uses: actions/setup-node@v3.6.0
  #       with:
  #         node-version: 18

  #     - name: 📥 Download deps
  #       uses: bahmutov/npm-install@v1
  #       with:
  #         useLockFile: false
  #         working-directory: ./staff

  #     - name: 🔬 Lint
  #       run: npm --prefix staff run lint

  # No typescript to typecheck yet!
  # typecheck:
  #   name:  ʦ Typecheck
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: ⬇️ Checkout repo
  #       uses: actions/checkout@v3

  #     - name: ⎔ Setup node
  #       uses: actions/setup-node@v3.6.0
  #       with:
  #         node-version: 18

  #     - name: 📥 Download deps
  #       uses: bahmutov/npm-install@v1
  #       with:
  #         useLockFile: false
  #         working-directory: ./staff

  #     - name: 🔎 Type check
  #       run: npm --prefix staff  run typecheck --if-present

  format-check:
    name: 🪞 Prettier
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          working-directory: ./staff

      - name: 🥺 Prettier Format Check
        run: npm --prefix staff run format:check

  playwright:
    name: 🎭 Playwright
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          working-directory: ./participant

      - name: 🐳 Run Playwright in Docker Compose
        run: npm run e2e
        working-directory: participant

      - name: 🗃 Archive test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: participant/test-results
