name: 🎭 Playwright snapshots

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "The app with Playwright snapshots to update"
        required: true
        default: "participant"
        type: choice
        options:
          - participant
          - staff

env:
  APP_NAME: ${{ inputs.app_name || 'participant' }}

# Need to repeat the expression since env.WHATEVER is not accessible in this context
concurrency: playwright-${{ github.ref_name }}-${{ inputs.app_name || 'participant' }}

jobs:
  snapshots:
    name: 🎭 Playwright snapshots
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3
        with:
          # Personal access token is required to get this workflow to trigger other workflows, such as CI
          # See https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs
          token: ${{ secrets.PAT }}
          # Make sure to checkout the correct branch
          ref: ${{ github.head_ref }}

      - name: ⎔ Setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          working-directory: ./${{ env.APP_NAME }}

      - name: 🎭 Install Playwright browsers
        run: npx playwright install --with-deps

      - name: 📸 Take Playwright snapshots
        run: npx playwright test --update-snapshots
        working-directory: ${{ env.APP_NAME }}

      - name: 💾 Save Playwright snapshots
        # Do not allow save to main branch
        if: github.ref != 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update playwright snapshots
          # Save only snapshots for the selected app
          file_pattern: '${{ env.APP_NAME }}/e2e/*.png'
